import type { AnalyzeResponse } from "./mock-analyze";
import { fetchPaper, type PaperResponse } from "./api";

export async function downloadResearchPaper(question: string, data: AnalyzeResponse) {
  // Fetch real structured content from backend
  const { default: jsPDF } = await import("jspdf");
  let paper: PaperResponse;
  try {
    paper = await fetchPaper(question);
  } catch (err) {
    console.warn("[pdf-export] backend unavailable, using fallback content", err);
    paper = buildFallbackPaper(question, data);
  }

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 56;
  const contentW = pageW - margin * 2;
  let y = margin;

  const ensureRoom = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Branding bar
  doc.setFillColor(20, 20, 24);
  doc.rect(0, 0, pageW, 36, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("WATSON & CRICK", margin, 23);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text("env-health research · lab notebook", pageW - margin, 23, { align: "right" });

  y = 72;

  // Title
  doc.setTextColor(20, 20, 24);
  doc.setFont("times", "italic");
  doc.setFontSize(20);
  const titleLines = doc.splitTextToSize(`"${paper.title}"`, contentW);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 24 + 6;

  // Meta line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(110, 110, 120);
  doc.text(
    `Generated ${new Date(paper.generated_at).toLocaleString()}  ·  n = ${paper.statistical_findings.n.toLocaleString()}  ·  p = ${paper.statistical_findings.p_value.toFixed(4)}  ·  r = ${paper.statistical_findings.pearson_r.toFixed(3)}`,
    margin,
    y,
  );
  y += 22;

  // Divider
  doc.setDrawColor(20, 20, 24);
  doc.setLineWidth(1);
  doc.line(margin, y, pageW - margin, y);
  y += 22;

  const section = (title: string, body: string | string[]) => {
    ensureRoom(60);
    doc.setTextColor(20, 20, 24);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(title.toUpperCase(), margin, y);
    y += 14;
    doc.setFont("times", "normal");
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 48);
    const text = Array.isArray(body) ? body.map((b) => `• ${b}`).join("\n") : body;
    const lines = doc.splitTextToSize(text, contentW);
    for (const line of lines) {
      ensureRoom(16);
      doc.text(line, margin, y);
      y += 15;
    }
    y += 12;
  };

  section("Abstract", paper.abstract);
  section("Methodology", paper.methodology);
  section("Datasets used", paper.datasets_used);
  section("Statistical findings", [
    `Pearson r = ${paper.statistical_findings.pearson_r.toFixed(3)}`,
    `p-value = ${paper.statistical_findings.p_value.toFixed(4)}`,
    `Sample size = ${paper.statistical_findings.n.toLocaleString()}`,
    `Confidence = ${paper.statistical_findings.confidence}`,
    ...(paper.statistical_findings.slope != null
      ? [`Slope = ${paper.statistical_findings.slope.toFixed(4)}`]
      : []),
  ]);
  section(
    "Hypotheses",
    paper.hypotheses.map(
      (h) => `[${h.confidence}] ${h.hypothesis} — ${h.mechanism}`,
    ),
  );
  section("Biological interpretation", paper.biological_interpretation);
  section("Genes implicated", paper.genes.join(", "));
  section("Limitations", paper.limitations);
  section("Conclusion", paper.conclusion);

  // Footer on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 150);
    doc.text(
      `Generated by Watson & Crick · ${new Date().toLocaleString()}`,
      margin,
      pageH - 24,
    );
    doc.text(`Page ${i} of ${pageCount}`, pageW - margin, pageH - 24, { align: "right" });
  }

  const safeName =
    question
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 60) || "watson-crick-paper";
  doc.save(`${safeName}.pdf`);
}

// ── Fallback when backend is unreachable ──────────────────────────
function buildFallbackPaper(question: string, data: AnalyzeResponse): PaperResponse {
  const r = data.stats?.r ?? 0;
  const p = data.stats?.p ?? 1;
  const n = data.stats?.n ?? 0;
  return {
    title: question,
    abstract: `This study examined the relationship between ${data.env_factor} and ${data.outcome} using real-world environmental and health datasets from San Diego County. A Pearson correlation of r=${r} (p=${p}, n=${n}) was observed.`,
    methodology: `Daily ${data.env_factor} measurements were matched with county-level ${data.outcome} prevalence data. Pearson correlation was computed after removing missing values across ${n} time points.`,
    datasets_used: data.datasets_used ?? [],
    statistical_findings: {
      pearson_r: r,
      p_value: p,
      n,
      confidence: data.stats?.confidence ?? "LOW",
      slope: data.stats?.slope ?? null,
    },
    hypotheses: data.hypotheses ?? [],
    biological_interpretation: data.hypotheses?.[0]?.mechanism ?? "",
    limitations: [
      `Sample size limited to ${n} observations.`,
      "Ecological correlation cannot establish individual-level causation.",
      "Unmeasured confounders (indoor exposure, occupation) not controlled.",
    ],
    conclusion: `Our analysis suggests a ${(data.stats?.confidence ?? "low").toLowerCase()}-confidence association between ${data.env_factor} and ${data.outcome}. Replication in larger cohorts is recommended.`,
    genes: (data.graph?.nodes ?? [])
      .filter((nd: { type: string }) => nd.type === "gene")
      .map((nd: { label: string }) => nd.label),
    generated_at: new Date().toISOString(),
  };
}